version: '3.4'

services:
  nginx:
    image: nginx:1.24
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    environment:
      - VIRTUAL_HOST=laravel.local
    depends_on:
      - php

  php:
    build: ./docker/php
    volumes:
      - .:/var/www/html

  db:
    image: mariadb:10.3.35
    environment:
      - MARIADB_ROOT_PASSWORD=secret
      - MARIADB_DATABASE=laravel
    volumes:
      - db:/var/lib/mysql

volumes:
  db: